version: "3.7"

services:
  app:
    container_name: app
    build: ./app
    env_file:
      - .env
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: python bot.py
  postgres:
    image: postgres:13.4
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    restart: always

volumes:
  db-data:
